<a href="https://colab.research.google.com/github/devkegovind/Python-Pandas/blob/main/Pandas_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1 align='center'>PANDAS NUMPY</h1>

NumPy, which stands for Numerical Python, is a library consisting of multidimensional array object and a collection of routines for processing those arrays. Using NumPy, mathematical and logical operations on arrays can be performed. 

<h2>Operations Using NumPy</h2>

- Mathematical and Logical Operations on arrays.
- Fourier transforms and routines for shape manipulation.
- Operations related to linear algebra. NumPy has in-built functions for linear algebra and random number generation.

<h2>NumPy - A Replacement for MatLab</h2>

NumPy is often used along with packages like <b>Scipy</b>  (Scientific Python) and <b>Mat-plotlib</b> (plotting library). This combination is widely used as a replacement for MatLab, a popular platform for technical computing. However, Python alternative to MatLab is now seen as a modern and complete programming language.

It is open source, which is an added advantage of NumPy. Standard Pyton distribution doesn't come bundles with NumPy module. A lightweight alternative is to install NumPy Using popular Python package installer, <b>pip</b> 

`pip install numpy`

<h3>NumPy - Ndarray Object</h3>

The most important object defined in NumPy is an N-dimensional array type called <b>ndarray</b>. It describe the collection of items of the same type. Items in the collection can be accessed using a zero-based index.

Every item in an ndarray takes the same size of block in the memory. Each element in ndarray is an object of data-type object(called dtype).

Any item extracted from ndarray object (by slicing) is represented by a Python object of one of array scalar types. The following diagram shows a relationship between ndaary, data type object(dtype) and array scalar type -

The basic ndarray is created using an array function in NumPy as Follows- 

`numpy.array`

It creates an ndarray from any object exposing array interface, or from any method that returns an array.

`numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndim = 0)`

Create a NumPy ndarray Object

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

arr

array([1, 2, 3, 4, 5])

In [2]:
type(arr)

numpy.ndarray

In [3]:
arr = np.array((1, 2, 3, 4, 5))
arr

array([1, 2, 3, 4, 5])

<h3>Dimensions in Arrays</h3>

<h4>0-D Arrays</h4>

0-D arrays, or Scalars, are the elements in an array. Each Value in an array is a 0-D array.

Create a 0-D array with value 42

In [4]:
arr = np.array(42)
arr

array(42)

<h4>1-D Arrays</h4>

An array that has 0-D arrays as its elements is called Uni-dimensional or 1-D Array.

In [5]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

<h4>2-D Arrays</h4>

An array that has 1-D arrays as its elements is called 2-D array. These often used to represent matrix or 2nd order tensors.

In [6]:
arr = np.array([[1, 2, 3], [4, 5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
a = np.array([1, 2, 3, 4, 5], ndmin = 2)
a

array([[1, 2, 3, 4, 5]])

<h4>3-D Arrays</h4>

An array that has 2-D arrays(matrices) as its elements is called 3-D array.
These are often used to represent a 3rd order tensor.

In [8]:
arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
arr

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

The <b>ndarray</b> object consist of contiguous one-dimensional segments of computer memory, combined with an indexing scheme that maps each item to a location in the memory block. The memory block holds the elements in a row-major order(C style) or a column-major order(FORTRAN or MatLab style).

<h4>Check Number of Dimensions?</h4>

NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [9]:
a = np.array(42)

b = np.array([1, 2, 3, 4, 5])

c = np.array([[1, 2, 3], [4, 5, 6]])

d = np.array([[[1, 2, 3],[4, 5, 6], [7, 8, 9]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


<h4>Higher Dimensional Arrays</h4>

An array can have any number of dimensions.
When the array is created, you can define the number of dimensions by using the `ndmin` argument.

In [10]:
arr = np.array([1, 2, 3, 4], ndmin = 5)
arr

array([[[[[1, 2, 3, 4]]]]])

In [11]:
print(arr.ndim)

5


In this array the innermost dimension (5th dim) has 4 elements, the 4th dim has 1 element that is the vector, the 3rd dim has 1 element that is the matrix with the vector, the 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array.

<h2 align='center'>NumPy - Data Types</h2>

NumPy supports a much greater variety of numerical types than Python does. The following table shows different scalar data types defined in NumPy.
![image.png](attachment:image.png)
![image-2.png](attachment:image-2.png)

NumPy numerical types are instances of dtype (data-type) objects, each having unique characteristics. The dtypes are available as np.bool_, np.float32, etc.

<h4>Data Type Objects (dtype)</h4>

A data type object describes interpretation of fixed block of memory corresponding to an array, depending on the following aspects −

- Type of data (integer, float or Python object)

- Size of data

- Byte order (little-endian or big-endian)

In case of structured type, the names of fields, data type of each field and part of the memory block taken by each field.

If data type is a subarray, its shape and data type

The byte order is decided by prefixing '<' or '>' to data type. '<' means that encoding is little-endian (least significant is stored in smallest address). '>' means that encoding is big-endian (most significant byte is stored in smallest address).

A dtype object is constructed using the following syntax −

`numpy.dtype(object, align, copy)`

In [12]:
dt = np.dtype(np.int32)
dt

dtype('int32')

int8, int16, int32, int64 can be replaced by equivalent string 'i1', 'i2','i4', etc. 

In [13]:
dt = np.dtype('i4')
dt

dtype('int32')

In [14]:
dt = np.dtype([('age', np.int8)])
dt

dtype([('age', 'i1')])

In [15]:
dt = np.dtype([('age', np.int8)])

a = np.array([(10,), (20,), (30,)], dtype = dt)

a

array([(10,), (20,), (30,)], dtype=[('age', 'i1')])

In [16]:
a['age']

array([10, 20, 30], dtype=int8)

The following examples define a structured data type called <b>student</b> with a string field 'name', an <b>integer field</b> 'age' and a <b>float field</b> 'marks'. This dtype is applied to ndarray object.

In [17]:
student = np.dtype([('name', 'S20'), ('age', 'i1'), ('marks', 'f4')])
student

dtype([('name', 'S20'), ('age', 'i1'), ('marks', '<f4')])

In [18]:
a = np.array([('abc', 21, 50), ('xyz', 18, 75)], dtype = student)
a

array([(b'abc', 21, 50.), (b'xyz', 18, 75.)],
      dtype=[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')])

<h2 align='center'>NumPy - Array Attributes</h2>

<h4>ndarray.shape</h4>

This array attribute returns a tuple consisting of array dimensions. It can also used to resize the array.

In [19]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.shape

(2, 3)

This resize the array

In [20]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.shape = (3, 2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

NumPy also provides a reshape function to resize an array.

In [21]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = a.reshape(3, 2)
b

array([[1, 2],
       [3, 4],
       [5, 6]])

<h4>ndarray.ndim</h4>

This array attribute returns the number of array dimensions.

In [22]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [23]:
a.ndim

1

In [24]:
b = a.reshape(2, 4, 3)
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

<h4>numpy.itemsize</h4>

This array attribute returns the length of each element of array in bytes.

dtype of array is int8 (1 byte)

In [25]:
x = np.array([1, 2, 3, 4, 5], dtype = np.int8)
x.itemsize

1

In [26]:
type(x)

numpy.ndarray

dtype of array is now float32 (4 bytes)

In [27]:
x = np.array([1, 2, 3, 4], dtype = np.float32)
x.itemsize

4

dtype of array is now int32 ( 4 bytes)

In [28]:
x = np.array([1, 2, 3, 4], dtype = np.int32)
x.itemsize

4

<h2 align='center'> NumPy - Array Creation Routines</h2>

A new <b>ndarray</b> object can be constructed by any of the following array creation routines or using a low-level ndarray constructor.

<h4>numpy.empty</h4>

It creates an uninitialized array of specified shape and dtype. It uses the following constructor-

`numpy.empty(shape, dtype = float, order = 'C')`

![image.png](attachment:image.png)

In [29]:
x = np.empty([3, 2], dtype = int)
x

array([[57821296,        0],
       [       0,        0],
       [       0,        0]])

<h4>Note</h4>The elements in an array show random values as they are not initialized.

<h4>numpy.zeros</h4>

Returns a new array of specified size, filled with zeros.

`numpy.zeros(shape, dtype = float, order = 'C')`

In [30]:
x = np.zeros(5)
x

array([0., 0., 0., 0., 0.])

In [31]:
x = np.zeros((5,), dtype = np.int)
x

<ipython-input-31-e4f750252e37>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.zeros((5,), dtype = np.int)


array([0, 0, 0, 0, 0])

In [32]:
x = np.zeros((2,2), dtype = [('x', 'i4'), ('y', 'i4')])
x

array([[(0, 0), (0, 0)],
       [(0, 0), (0, 0)]], dtype=[('x', '<i4'), ('y', '<i4')])

<h4>numpy.ones</h4>

Returns a new array of specified size and type, filled with ones.

`numpy.ones(shape, dtype = None, order = 'C')`

In [33]:
x = np.ones(5)
x

array([1., 1., 1., 1., 1.])

In [34]:
x = np.ones([2, 2], dtype = int)
x

array([[1, 1],
       [1, 1]])

<h2 align='center'>NumPy - Array From Numerical Ranges</h2>

<h4>numpy.arange</h4>

This function returns an <b>ndarray</b> object containing evenly spaced values within a given range. The format of the function is as follows-

`numpy.arange(start, stop, step, dtype)`

The constructor takes the following parameters.

![image.png](attachment:image.png)

In [35]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [36]:
x = np.arange(5, dtype = float)
x

array([0., 1., 2., 3., 4.])

Start and Stop Parameter Set

In [37]:
x = np.arange(10, 20, 2)
x

array([10, 12, 14, 16, 18])

<h4>numpy.linspace</h4>

This function is similar to <b>arange()</b> function, instead of step size, the number of evenly spaced values between the interval is specified. The usage of this function is as follows-

`numpy.linspace(start, stop, num, endpoint, restep, dtype)`

The constructor takes the following parameters.
![image.png](attachment:image.png)

In [38]:
x = np.linspace(10, 20, 5)
x

array([10. , 12.5, 15. , 17.5, 20. ])

Endpoint set to False

In [39]:
x = np.linspace(10, 20, 5, endpoint = False)
x

array([10., 12., 14., 16., 18.])

Find retstep value

In [40]:
x = np.linspace(1, 2, 5, retstep = True)
x

(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)

<h4>numpy.logspace</h4>

This function returns an <b>ndarray</b> object that contains the numbers that are evenly spaced on log scale. Start and Stop endpoints of the scale are indices of the base, usually 10.

`numpy.logspace(start, stop, num, endpoit, base, dtype)`

In [41]:
import numpy as np

# Default base is 10
a = np.logspace(1.0, 2.0, num = 10)
a

array([ 10.        ,  12.91549665,  16.68100537,  21.5443469 ,
        27.82559402,  35.93813664,  46.41588834,  59.94842503,
        77.42636827, 100.        ])

Set base of log space to 2

In [42]:
import numpy as np
a = np.logspace(1, 10, num = 10, base = 2)
a

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

<h2 align='center'>NumPy - Indexing & Slicing</h2>

Contents of ndarray object can be accessed and modified by indexing or slicing, just like Python's in-built container objects.

As mentioned earlier, items in ndarray object follows zero-based index. Three types of indexing methods are available − <b>field access, basic slicing and advanced indexing.</b>

Basic slicing is an extension of Python's basic concept of slicing to n dimensions. A Python slice object is constructed by giving <b>start, stop, and step</b> parameters to the built-in slice function. This slice object is passed to the array to extract a part of array.

In [43]:
import numpy as np
a = np.arange(10)
s = slice(2, 7, 2)
a[s]

array([2, 4, 6])

In [44]:
import numpy as np
a = np.arange(10)
b = a[2:7:2]
b

array([2, 4, 6])

Slice Single item

In [45]:
import numpy as np
a = np.arange(10)
b = a[5]
b

5

Slice items starting from index

In [46]:
import numpy as np
a = np.arange(10)
a[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

Slice items between indexes

In [47]:
import numpy as np
a = np.arange(10)
a[2:5]

array([2, 3, 4])

In [48]:
import numpy as np
a = np.array([[1, 2, 3], [3, 4, 5], [4, 5, 6]])
a[1:]

array([[3, 4, 5],
       [4, 5, 6]])

<h2 align='center'>NumPy - Advanced Indexing</h2>

It is possible to make a selection from ndarray that is a non-tuple sequence, ndarray object of integer or Boolean data type, or a tuple with at least one item being a sequence object. Advanced indexing always returns a copy of the data. As against this, the slicing only presents a view.

There are two types of advanced indexing − Integer and Boolean.

<h4>Integer Indexing</h4>
This mechanism helps in selecting any arbitrary item in an array based on its Ndimensional index. Each integer array represents the number of indexes into that dimension. When the index consists of as many integer arrays as the dimensions of the target ndarray, it becomes straightforward.

In the following example, one element of specified column from each row of ndarray object is selected. Hence, the row index contains all row numbers, and the column index specifies the element to be selected.

In [49]:
x = np.array([[1, 2], [3, 4], [5, 6]])
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [50]:
x[[0, 1, 2], [0, 1, 0]]

array([1, 4, 5])

In [51]:
x = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [52]:
rows = np.array([[0, 0], [3, 3]])
cols = np.array([[0, 2], [0, 2]])

y = x[rows, cols]
y

array([[ 0,  2],
       [ 9, 11]])

In [53]:
x = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

<h4>Slicing</h4>

In [54]:
z = x[1:4, 1:3]
z

array([[ 4,  5],
       [ 7,  8],
       [10, 11]])

<h4>Slicing Using Advanced index For Column</h4>

In [55]:
y = x[1:4, [1, 2]]
y

array([[ 4,  5],
       [ 7,  8],
       [10, 11]])

<h4>Boolean Array Indexing</h4>

This type of advanced indexing is used when the resultant object is meant to be the result of Boolean Operations, such as comparison operators.

<h4>Items greater than 5 are returned as a result of Boolean Indexing</h4>

In [56]:
x = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [57]:
[x > 5]

[array([[False, False, False],
        [False, False, False],
        [ True,  True,  True],
        [ True,  True,  True]])]

In [58]:
x[x > 5]

array([ 6,  7,  8,  9, 10, 11])

<h4>NaN(Not a Number) elements are omitted by using ~(complement operator)</h4>

In [59]:
a = np.array([np.nan, 1, 2, np.nan, 3, 4, 5])
a[~np.isnan(a)]

array([1., 2., 3., 4., 5.])

<h4>How To filter out the non-complex elements from an array.</h4>

In [60]:
a = np.array([1,2+6j, 5, 3.5+5j])
a[np.iscomplex(a)]

array([2. +6.j, 3.5+5.j])

<h3, align='center'>NumPy - Broadcasting</h3>

The term <b>broadcasting</b> refers to the ability of NumPy to treat arrays of different shapes during arithmetic operations. Arithmetic operations on arrays are usually done on corresponding elements. If two arrays are of exactly the same shape, then these operations are smoothly performed.

In [61]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

c = a * b
c

array([ 10,  40,  90, 160])

If the dimensions of two arrays are dissimilar, element-to-element operations are not possible. However, operations on arrays of non-similar shapes is still possible in NumPy, because of the <b>broadcasting</b> capability. The smaller array is <b>broadcast</b> to the size of the larger array so that they have compatible shapes.

Broadcasting is possible if the following rules are satisfied -

- Array with smaller <b>ndim</b> than the other is prepended with '1' in its shape.
- Size in each dimension of the output shape is maximum of the input sizes in that dimension.
- An input can be used in calculation, if its size in a particular dimension matches the output size or its value is exactly 1.
- If an input has a dimension size of 1, the first data entry in that dimension is used for all calculations along that dimensions.

A set of arrays is said to be <b>broadcastable</b> if the above rules produces a valid result and one of the following is true -
- Arrays have exactly the same shape.
- Arrays have the same number of dimensions and the length of each dimensions is either a common length or 1.
- Arrays having too few dimensions can have its shape prepended with a dimension of length 1, so that the above stated property is true.


In [62]:
a = np.array([[0.0, 0.0, 0.0], [10.0, 10.0, 10.0], [20.0, 20.0, 20.0], [30.0, 30.0, 30.0]])
b = np.array([1.0, 2.0, 3.0])

a

array([[ 0.,  0.,  0.],
       [10., 10., 10.],
       [20., 20., 20.],
       [30., 30., 30.]])

In [63]:
b

array([1., 2., 3.])

In [64]:
a + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

The following figure demonstrates how array <b>b</b> is broadcast to become compatible with <b>a</b>.

![image.png](attachment:image.png)

<h2 align='center'>NumPy - Iterating Over Array</h2>

NumPy package contains an iterator object <b>numpy.nditer</b>. It is efficient multidimensional iterator object using which it is possible to iterate over an array. Each element of an array is visited using Python's standard interface.

Let us create a 3X4 using arange() function and iterate over it using <b>nditer</b>

In [65]:
import numpy as np

a = np.arange(0, 60, 5)
a

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [66]:
a = a.reshape(3, 4)
a

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [67]:
for i in np.nditer(a):
    print(i)

0
5
10
15
20
25
30
35
40
45
50
55


iterating over the transpose of the above array.

In [68]:
import numpy as np

a = np.arange(0, 60, 5)
a = a.reshape(3, 4)
a

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [69]:
b = a.T
b

array([[ 0, 20, 40],
       [ 5, 25, 45],
       [10, 30, 50],
       [15, 35, 55]])

In [70]:
for i in np.nditer(b):
    print(i)

0
5
10
15
20
25
30
35
40
45
50
55


<h4>Iteration Order</h4>

If the same elements are stored using F-style order, the iterator chooses the more efficient way
of iterating over an array.


In [71]:
import numpy as np

a = np.arange(0, 60, 5)
a = a.reshape(3, 4)
a

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

Transpose of a

In [72]:
b = a.T
b

array([[ 0, 20, 40],
       [ 5, 25, 45],
       [10, 30, 50],
       [15, 35, 55]])

Sorted in C-style order

In [73]:
c = b.copy(order = 'C')
c

array([[ 0, 20, 40],
       [ 5, 25, 45],
       [10, 30, 50],
       [15, 35, 55]])

In [74]:
for i in np.nditer(c):
    print(i)

0
20
40
5
25
45
10
30
50
15
35
55


Sorted in F-style order

In [75]:
c = b.copy(order = 'F')
c

array([[ 0, 20, 40],
       [ 5, 25, 45],
       [10, 30, 50],
       [15, 35, 55]])

In [76]:
for x in np.nditer(c):
    print(x)

0
5
10
15
20
25
30
35
40
45
50
55


It is possible to force nditer object to use a specific order by explicitly mentioning it.

In [77]:
import numpy as np

a = np.arange(0, 60, 5)
a = a.reshape(3, 4)
a

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [78]:
for x in np.nditer(a, order = "c"):
    print(x)

0
5
10
15
20
25
30
35
40
45
50
55


In [79]:
for x in np.nditer(a, order = 'F'):
    print(x)

0
20
40
5
25
45
10
30
50
15
35
55


<h2 align='center'>NumPy - Mathematical Functions</h2>

Quite understandably, NumPy contains a large number of various mathematical Operations. NumPy provides standard trignometric functions, functions for arithmetic operations, handling complex numbers, etc.

<h4>Trigonometric Functions</h4>

NumPy has standard trignometric functions which return trignometric ratios for a given angle in radians.

In [80]:
import numpy as np

a = np.array([0, 30, 45, 60, 90])
a

array([ 0, 30, 45, 60, 90])

Sine of Different angles:

Convert to Radians by Multiplying with pi/180

In [81]:
print(np.sin(a*np.pi/180))

[0.         0.5        0.70710678 0.8660254  1.        ]


Cosine values for angles in array

In [82]:
print(np.cos(a*np.pi/180))

[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


Tangent values for given angles

In [83]:
print(np.tan(a*np.pi/180))

[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


<b>arcsin, arcos,</b> and <b>artan</b> functions return the trignometric inverse of sin, cos, and tan of the given angle. The result of these functions can be verified by <b>numpy.degrees() function</b> by converting radians to degrees.

In [84]:
import numpy as np

a = np.array([0, 30, 45, 60, 90])
a

array([ 0, 30, 45, 60, 90])

Array Containing sine Values

In [85]:
sin = np.sin(a*np.pi/180)
print(sin)

[0.         0.5        0.70710678 0.8660254  1.        ]


Compute sine inverse of angles. Returned values are in radians.

In [86]:
inv = np.arcsin(sin)
inv

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

Check result by converting to degrees

In [87]:
print(np.degrees(inv))

[ 0. 30. 45. 60. 90.]


arccos and arctan functions behave similarly

In [88]:
cos = np.cos(a*np.pi/180)
cos

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [89]:
inv = np.arccos(cos)
inv

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [90]:
np.degrees(inv)

array([ 0., 30., 45., 60., 90.])

In [91]:
tan = np.tan(a*np.pi/180)
tan

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [92]:
inv = np.arctan(tan)
inv

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [93]:
np.degrees(inv)

array([ 0., 30., 45., 60., 90.])

<h3>Functions For Rounding</h3>

<h4>numpy.around</h4>

This is a function that returns the value rounded to the desired precision. The function takes the following parameters.

![image.png](attachment:image.png)

In [94]:
import numpy as np

a = np.array([1.0, 5.55, 123, 0.567, 25.532])

a

array([  1.   ,   5.55 , 123.   ,   0.567,  25.532])

After Rounding

In [95]:
np.around(a)

array([  1.,   6., 123.,   1.,  26.])

In [96]:
np.around(a, decimals = 1)

array([  1. ,   5.6, 123. ,   0.6,  25.5])

In [97]:
np.around(a, decimals = -1)

array([  0.,  10., 120.,   0.,  30.])

<h4>numpy.floor()</h4>

This function returns the largest integer not greater than the input parameter. The floor of the <b>scalar x</b> is the largest <b>integer i,</b> such that <b>i<=x</b>. Note that in Python, flooring always is rounded away from 0.

In [98]:
import numpy as np

a = np.array([-1.7, 1.5, -0.2, 0.6, 10])
a

array([-1.7,  1.5, -0.2,  0.6, 10. ])

In [99]:
np.floor(a)

array([-2.,  1., -1.,  0., 10.])

<h4>numpy.ceil()</h4>

The ceil() function returns the ceiling of an input value, i.e. the ceil of the <b>scalar x</b> is the smallest <b>integer i,</b> such that <b>i>=x.</b>

In [100]:
import numpy as np

a = np.array([-1.7, 1.5, -0.2, 0.6, 10])
a

array([-1.7,  1.5, -0.2,  0.6, 10. ])

In [101]:
np.ceil(a)

array([-1.,  2., -0.,  1., 10.])

<h2 align='center'>NumPy - Matrix Library</h2>

NumPy packages contains a Matrix library <b>numpy.matlib</b>. This module has functions that return matrices instead of ndarray objects.

<h4>matlib.empty()</h4>

The <b>matlib.empty</b> function returns a new matrix without initializing the entries, The function takes the following parameters.

`numpy.matlib.empty(shape, dtype, order)`

In [102]:
import numpy.matlib
import numpy as np

print(np.matlib.empty((2, 2))) # filled with random data

[[ 1.  2.]
 [ 1. 10.]]


<h4>numpy.matlib.zeros()</h4>

This function returns the matrix filled with zeros.


In [103]:
np.matlib.zeros((2, 2))

matrix([[0., 0.],
        [0., 0.]])

<h4>numpy.matlib.ones()</h4>

This function returns the matrix filled with 1s.

In [104]:
np.matlib.ones((2, 2))

matrix([[1., 1.],
        [1., 1.]])

<h4>numpy.matlib.eye()</h4>

This function returns a matrix with 1 along the diagonal elements and the zeros elsewhere. The function takes the following parameters.

`numpy.matlib.eye(n, M, k, dtype)`

In [105]:
np.matlib.eye(n=3, M=4, k=0, dtype = float)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

<h4>numpy.matlib.identity()</h4>

The <b>numpy.matlib.identity()</b> function returns the Identity matrixof the given size. An identity matrix is a square matrix with all diagonal elements as 1.

In [106]:
np.matlib.identity(5, dtype = float)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

<h4>numpy.matlib.rand()</h4>

The <b>numpy.matlib.rand()</b> function returns a matrix of the given size filled with random values.

In [107]:
np.matlib.rand(3, 3)

matrix([[0.08583226, 0.91406137, 0.74697624],
        [0.3359417 , 0.05842962, 0.71678573],
        [0.15499558, 0.17449422, 0.9888598 ]])

In [108]:
i = np.matrix('1,2;3,4')
i

matrix([[1, 2],
        [3, 4]])

<h2 align='center'>NumPy - Sort, Search & Counting Function</h2>

A variety of sorting related functions are available in NumPy. These sorting functions implement different sorting algorithms, each of them characterized by the speed of execution, worst case performance, the workspace required and the stability of algorithms. Following table shows the comparison of these sorting algorithms.

<h4>numpy.sort()</h4>

The sort() function returns a sorted copy of the input array. It has the following parameters -

`numpy.sort(a, axis, kind, order)`


In [109]:
import numpy as np

a = np.array([[3, 7], [9, 1]])
a

array([[3, 7],
       [9, 1]])

In [110]:
np.sort(a)

array([[3, 7],
       [1, 9]])

In [111]:
np.sort(a, axis = 0)

array([[3, 1],
       [9, 7]])

Order parameter in sort Function

In [112]:
dt = np.dtype([('name', 'S10'), ('age', int)])
a = np.array([('ram', 21), ('anil', 25), ('ravi', 17), ('amar', 27)], dtype = dt)
a

array([(b'ram', 21), (b'anil', 25), (b'ravi', 17), (b'amar', 27)],
      dtype=[('name', 'S10'), ('age', '<i8')])

In [113]:
np.sort(a, order = 'name')

array([(b'amar', 27), (b'anil', 25), (b'ram', 21), (b'ravi', 17)],
      dtype=[('name', 'S10'), ('age', '<i8')])

<h4>numpy.argsort()</h4>

The <b>numpy.argsort()</b> function performs an indirect sort on input array, along the given axis and using a specified kind of sort to return the array of indices of data. This indices array is used to construct the sorted array.

In [114]:
import numpy as np
x = np.array([3, 1, 2])
x

array([3, 1, 2])

In [115]:
y = np.argsort(x)
y

array([1, 2, 0])

In [116]:
x[y]

array([1, 2, 3])

In [117]:
for i in y:
    print(x[i])

1
2
3


<h4>numpy.lexsort()</h4>

Function perfomrs an indirect sort using a sequence of keys. The keys can be seen as a column in a spreadsheet. The function returns an array of indices, using which the sorted data can be obtained. Note, that the last key happens to the primary key of sort.

In [118]:
import numpy as np

nm = ('ram', 'anil', 'ravi', 'amar')
dv = ('f.y.', 's.y.', 's.y.', 'f.y.')
ind = np.lexsort((dv, nm))
ind

array([3, 1, 0, 2])

In [119]:
print([nm[i] + "," + dv[i] for i in ind])

['amar,f.y.', 'anil,s.y.', 'ram,f.y.', 'ravi,s.y.']


<h4>numpy.argmax() and numpy.argmin()</h4>

These two functions return the indices of maximum and minimum elements respectively along the given axis.

In [120]:
import numpy as np

a = np.array([[[30, 40, 70], [80, 20, 10], [50, 90, 60]]])
a

array([[[30, 40, 70],
        [80, 20, 10],
        [50, 90, 60]]])

In [121]:
np.argmax(a)

7

In [122]:
np.argmin(a)

5

Index of Maximum Number in Flattened Array

In [123]:
a.flatten()

array([30, 40, 70, 80, 20, 10, 50, 90, 60])

Array containing indices of maximum along axis 0

In [124]:
maxindex1 = np.argmax(a, axis = 0)
maxindex1

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

Array containing indices of maximum along axis 1

In [125]:
maxindex2 = np.argmax(a, axis = 1)
maxindex2

array([[1, 2, 0]])

Applying argmin() function

In [126]:
minindex = np.argmin(a)
minindex

5

Flattened array

In [127]:
a.flatten()[minindex]

10

Flattened array along axis 0

In [128]:
minindex = np.argmin(a, axis = 0)
minindex

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

Flattened array along axis 1

In [129]:
minindex = np.argmin(a, axis =1)
minindex

array([[0, 1, 1]])

<h4>numpy.nonzero()</h4>

The <b>numpy.nonzero()</b> function returns the indices of non-zero elements in the input array.

In [130]:
import numpy as np

a = np.array([[30, 40, 0], [0, 20, 10], [50, 0, 60]])
a

array([[30, 40,  0],
       [ 0, 20, 10],
       [50,  0, 60]])

Applying nonzero() function

In [131]:
np.nonzero(a)

(array([0, 0, 1, 1, 2, 2]), array([0, 1, 1, 2, 0, 2]))

<h4>numpy.where()</h4>

The where() function returns the indices of elements in an input array where the given condition is satisfied.

In [132]:
import numpy as np

x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Indices of elements > 3

In [133]:
y = np.where(x > 3)
y

(array([1, 1, 2, 2, 2]), array([1, 2, 0, 1, 2]))

In [134]:
x[y]

array([4, 5, 6, 7, 8])

<h2 align = 'center'>NumPy - Statistical Functions</h2>

NumPy has quite a few useful statistical functions for finding minimum, maximum, percentile standard deviation and variance, etc. from the given elements in the array. The functions are explained as follow - 

<h4>numpy.amin() and numpy.amax()</h4>

These functions return the minimum and the maximum from the elements in the given array along the specified axis.

In [135]:
import numpy as np

a = np.array([[3, 7, 5], [8, 4, 3], [2, 4, 9]])
a

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

Applying amin() function

In [136]:
np.amin(a, 1)

array([3, 3, 2])

Applying amin() function again

In [137]:
np.amin(a, 0)

array([2, 4, 3])

Applying amax() function again

In [138]:
np.amax(a, axis = 0)

array([8, 7, 9])

In [139]:
np.amax(a, axis =1)

array([7, 8, 9])

<h4>numpy.ptp()</h4>

The <b>numpy.ptp()</b> function returns the range(maximum-minimum) of values along an axis.

In [140]:
import numpy as np

a = np.array([[3, 7, 5], [8, 4, 3], [2, 4, 9]])
a

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

In [141]:
np.ptp(a)

7

In [142]:
np.ptp(a, axis = 1)

array([4, 5, 7])

In [143]:
np.ptp(a, axis = 0)

array([6, 3, 6])

<h4>numpy.percentile()</h4>

Percentile (or a centile) is a measure used in statistice indicating the value below which a given percentage of observations in a group of observations fail. The function <b>numpy.percentile()</b> takes the following arguments.

`numpy.percentile(a, q, axis)`


In [144]:
import numpy as np

a = np.array([[30, 40, 70], [80, 20, 10], [50, 90, 60]])
a

array([[30, 40, 70],
       [80, 20, 10],
       [50, 90, 60]])

In [145]:
np.percentile(a, 50)

50.0

In [146]:
np.percentile(a, 50, axis = 0)

array([50., 40., 60.])

In [147]:
np.percentile(a, 50, axis = 1)

array([40., 20., 60.])

<h4>numpy.median()</h4>

<b>Median</b> is defined as the value seperating the higher half of a data sample from the lower half. The <b>numpy.median()</b> function is used as shown in the following program.

In [148]:
import numpy as np

a = np.array([[30, 65, 70], [80, 95, 10], [50, 90, 60]])
a

array([[30, 65, 70],
       [80, 95, 10],
       [50, 90, 60]])

In [149]:
np.median(a)

65.0

In [150]:
np.median(a, axis = 0)

array([50., 90., 60.])

In [151]:
np.median(a, axis = 1)

array([65., 80., 60.])

<h4>numpy.mean()</h4>

Arithmetic mean is the sum of elements along an axis divided by the number of elements. The <b>numpy.mean()</b> function returns the arithmetic mean of elements in the array. Iff the axis is mentioned, it is calculated along it.

In [152]:
import numpy as np

a = np.array([[1, 2, 3], [3, 4, 5], [4, 5, 6]])
a

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [153]:
np.mean(a)

3.6666666666666665

In [154]:
np.mean(a, axis = 0)

array([2.66666667, 3.66666667, 4.66666667])

In [155]:
np.mean(a, axis = 1)

array([2., 4., 5.])

<h4>standard Deviation</h4>

Standard Deviation is the square root of the average of squared deviations from mean. The formula for standard deviation is as follows -

$std = sqrt(mean(abs(x - x.mean())**2))$

if the array is [1, 2, 3, 4] then its mean is 2.5. Hence the squared deviations are [2.25, 0.25, 0.25, 2.25] and the square root of its mean divided by 4 i.e. sqrt(5/4) is 1.1180339887498949

In [156]:
import numpy as np

np.std([1, 2, 3, 4])

1.118033988749895

<h4>Variance</h4>
Variance is the average of squared deviations, i.e. <b>mean(abs(x - x.mean())**2)</b> In other words, the standard deviation is the square root of variance.

In [157]:
import numpy as np
np.var([1, 2, 3, 4])

1.25

<h2 align='center'>NumPy - Arithmetic Operations</h2>

Input arrays for performing arithmetic opertions such as add(), subtract(), multiply(), and divide() must be either of the same shape or should confirm to array broadcasting rules.

In [158]:
import numpy as np

a = np.arange(9, dtype = np.float).reshape(3, 3)
a

<ipython-input-158-a787d0199b3f>:3: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a = np.arange(9, dtype = np.float).reshape(3, 3)


array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [159]:
b = np.array([10, 10, 10])
b

array([10, 10, 10])

Add the two arrays

In [160]:
np.add(a, b)

array([[10., 11., 12.],
       [13., 14., 15.],
       [16., 17., 18.]])

Substract the two arrays

In [161]:
np.subtract(a, b)

array([[-10.,  -9.,  -8.],
       [ -7.,  -6.,  -5.],
       [ -4.,  -3.,  -2.]])

Multiply the two arrays

In [162]:
np.multiply(a,b)

array([[ 0., 10., 20.],
       [30., 40., 50.],
       [60., 70., 80.]])

Divide the two arrays

In [163]:
np.divide(a, b)

array([[0. , 0.1, 0.2],
       [0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8]])

<h4>numpy.reciprocal()</h4>

This function returns the reciprocal of argument, element-wise. For elements with absolute values larger than 1, the result is always 0 because of the way in which Python handles integer division. For integer 0, an overflow warning is issued.

In [164]:
import numpy as np

a = np.array([0.25, 1.33, 1, 0, 100])
a

array([  0.25,   1.33,   1.  ,   0.  , 100.  ])

After applying reciprocal function

In [165]:
np.reciprocal(a)

<ipython-input-165-8988e9a787cf>:1: RuntimeWarning: divide by zero encountered in reciprocal
  np.reciprocal(a)


array([4.       , 0.7518797, 1.       ,       inf, 0.01     ])

In [166]:
b = np.array([100], dtype = int)
b

array([100])

In [167]:
np.reciprocal(b)

array([0])

<h4>numpy.power()</h4>

This function treats elements in the first input array as base and returns it raised to the power of the corresponding element in the second input array.

In [168]:
import numpy as np

a = np.array([10, 100, 1000])
a

array([  10,  100, 1000])

Applying Power Function

In [169]:
np.power(a, 2)

array([    100,   10000, 1000000])

In [170]:
b = np.array([1, 2, 3])
b

array([1, 2, 3])

In [171]:
np.power(a, b)

array([        10,      10000, 1000000000])

<h4>numpy.mod()</h4>

This function returns the remainder of division of the corresponding elements in the input array. The function <b>numpy.remaider()</b> also produces the same result.

In [172]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([3, 5, 7])

In [173]:
a

array([10, 20, 30])

In [174]:
b

array([3, 5, 7])

Applying mod() function

In [175]:
np.mod(a, b)

array([1, 0, 2])

Applying remainder() function

In [176]:
np.remainder(a, b)

array([1, 0, 2])

The following functions are used to perform operations on array with complex numbers.

- <b>numpy.real()</b> - returns the real part of the complex data type argument.
- <b>numpy.imag()</b> - returns the imaginary part of the complex data type argument.
- <b>numpy.conj()</b> -returns the complex conjugate, which is obtained by changing the sign of the imaginary part.
- <b>numpy.angle()</b> - returns the angle of the complex argument. The function has degree parameter. If true, the angle in the degree is returned, otherwise the angle is in radians.

In [177]:
import numpy as np
a = np.array([-5.6j, 0.2j, 11., 1+1j])
a

array([-0.-5.6j,  0.+0.2j, 11.+0.j ,  1.+1.j ])

Applying real() Function

In [178]:
np.real(a)

array([-0.,  0., 11.,  1.])

Applying imag() Function

In [179]:
np.imag(a)

array([-5.6,  0.2,  0. ,  1. ])

Applying angle() Function

In [180]:
np.angle(a)

array([-1.57079633,  1.57079633,  0.        ,  0.78539816])

Applying conj() function

In [181]:
np.conj(a)

array([-0.+5.6j,  0.-0.2j, 11.-0.j ,  1.-1.j ])

Applying angle() Function again (result in degrees)

In [182]:
np.angle(a, deg = True)

array([-90.,  90.,   0.,  45.])

<h2 align='center'>NumPy - Copies & Views</h2>

While executing the functions, some of them return a copy of the input array, while some return the view. When the contents are physically stored in another location, it is <b>Copy</b>. If on the other hand, a different view of the same memory content is provided, we call it as <b>View</b>

<h4>No Copy</h4>

Simple assignments do not make the copy of array object. Instead, it uses the same id() of the original array to access it. The <b>id()</b> returns a universal identifier of Python object, similar to the pointer in C.

Furthermore, any changes in either gets reflected in the other. For example, the changing shape of one will change the shape of the other too.

In [183]:
import numpy as np

a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

Applying id() Function

In [184]:
id(a)

140089445530480

a is assigned to b

In [185]:
b = a

In [186]:
b

array([0, 1, 2, 3, 4, 5])

b has same id()

In [187]:
id(b)

140089445530480

Change the shape of b

In [188]:
b.shape = 3, 2
b

array([[0, 1],
       [2, 3],
       [4, 5]])

Shape of a also gets changed

In [189]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

<h4>View or Shallow Copy</h4>

NumPy has <b>ndarray.view()</b> method which is a new array object that looks at the same data of the original array. Unlike the earlier case, change in dimensions of the new array doesn't change dimensions of the original array.

In [190]:
import numpy as np

a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

Create view of a

In [191]:
b = a.view()

In [192]:
b

array([[0, 1],
       [2, 3],
       [4, 5]])

id () for both arrays are differents

In [193]:
id(a)

140089445559440

In [194]:
id(b)

140089445560016

Change the shape of b. It does not change the shape of a

In [195]:
b.shape = 2,3

In [196]:
b

array([[0, 1, 2],
       [3, 4, 5]])

shape of a

In [197]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

<h4>Deep Copy</h4>

The <b>ndarray.copy()</b> function creates a deep copy. It is a complete copy of the array and its data, and doesn't share with the original array.

In [198]:
import numpy as np

a = np.array([[10, 10], [2, 3], [4, 5]])
a

array([[10, 10],
       [ 2,  3],
       [ 4,  5]])

Create a Deep Copy of a

In [199]:
b = a.copy()
b

array([[10, 10],
       [ 2,  3],
       [ 4,  5]])

id() of both array are differents

In [200]:
id(a)

140089463012976

In [201]:
id(b)

140089463012208

Modified array b

In [202]:
b[0, 0] = 100

In [203]:
b

array([[100,  10],
       [  2,   3],
       [  4,   5]])

a remains changed

In [204]:
a

array([[10, 10],
       [ 2,  3],
       [ 4,  5]])